### ISSUE TITLE
Initial install UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by damieneichhorn** [bjarn/jale#21]
**Describe the bug**
Whenever I run jale install, I get an unhandled promise rejection in the end and no configuration or logging is created.

**To Reproduce**
1. Install jale globally with "npm install -g jale"
2. Run jale install
3. Choose domain: "test", Choose php7.4, Choose mysql8.0, Choose no services, Choose no tools/apps

**Expected behavior**
the install should finish normally

**Screenshots**
![image](https://user-images.githubusercontent.com/9391905/101817269-6dae5300-3b22-11eb-9832-0ad511bb03ef.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Terminal: iTerm
 - Shell: zsh
 - Jale version: 0.2.1

**Comment by bjarn** [comment]
Should be fixed in 299076f 👍 

Will publish a new release asap.

**Comment by bjarn** [comment]
Available in 0.3.0
